# Project 5 — The Design Matrix & The Structure of Neural Networks

**Why This Project Exists**
Projects 1–4 taught you the operations of machine learning:

- dot products
- gradients
- MSE
- cross‑entropy
- logistic regression
- hidden layers

But they didn’t yet reveal the structural object that unifies all of them:

### The Design Matrix **𝑋**

This project shows:

- Why ML always uses a matrix
- how OLS is literally a matrix equation
- how neural networks generalize it
- how batching is just slicing rows of 𝑋
- how shapes flow through the entire system

## What Is the Design Matrix?

**A design matrix is how machine learning represents data.**

Each row = one example = 
- n = number of examples (rows of X)

Each column = one feature
- d = number of features (columns of X)

So when we say:

𝑋
∈
𝑅
𝑛
×
𝑑

We mean:

- X has n rows (one per data point)
- X has d columns (one per feature)

![image](mathmatic/matrix_shape.jpg)

In [ ]:
import numpy as np

# 3 samples, 2 features
X = np.array([
    [1.0, 2.0],
    [3.0, 4.0],
    [5.0, 6.0]
])

X, X.shape

# this is the simplest possible design matrix.

(array([[1., 2.],
        [3., 4.],
        [5., 6.]]),
 (3, 2))

## From One Example to Many: Matrix Multiplication

Now suppose we want predictions for all n examples at once.

Instead of computing:

y^(1),y^(2),Y^(3)

In [5]:
x1, x2 = 3.0, 4.0
w1, w2 = 2.0, -1.0
b = 0.5

y_hat_scalar = w1*x1 + w2*x2 + b
y_hat_scalar

2.5

## Vector Dot Product

In [6]:
x = np.array([3.0, 4.0])
w = np.array([2.0, -1.0])
b = 0.5

y_hat_vector = w @ x + b
y_hat_vector


np.float64(2.5)

Matrix Form (All n Examples at Once)
Stack all examples into the design matrix:

𝑦^ = 𝑋𝑤 + 𝑏

In [7]:
X = np.array([
    [1.0, 2.0],
    [3.0, 4.0],
    [5.0, 6.0]
])

w = np.array([[2.0], [-1.0]])  # shape (d,1)
b = 0.5

y_hat_matrix = X @ w + b
y_hat_matrix


array([[0.5],
       [2.5],
       [4.5]])

### We have already seen this in Logistic Regression

The forward pass is:

- 𝑧 = 𝑋𝑤 + 𝑏
- 𝑦^ = 𝜎(𝑧)


Same structure — just with a sigmoid on top.

In [8]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

z = X @ w + b
y_hat_logistic = sigmoid(z)
y_hat_logistic


array([[0.62245933],
       [0.92414182],
       [0.98901306]])

### …we can finally show the big idea:

## A neural network layer is just a generalization of

𝑋𝑤 + 𝑏

Instead of one output, we compute h outputs:

𝑋𝑊 + 𝑏

Where:

𝑊 is (𝑑 × ℎ)

output is 

(𝑛 × ℎ)

In [9]:
# X: (n=3 samples, d=2 features)
X = np.array([
    [1.0, 2.0],
    [3.0, 4.0],
    [5.0, 6.0]
])

# W: (d=2 features, h=3 outputs)
W = np.array([
    [1.0, -1.0,  0.5],
    [0.5,  2.0, -1.5]
])

b = np.array([0.1, -0.2, 0.3])

Z = X @ W + b
Z, Z.shape


(array([[ 2.1,  2.8, -2.2],
        [ 5.1,  4.8, -4.2],
        [ 8.1,  6.8, -6.2]]),
 (3, 3))

In [10]:
# add an activation 
A = sigmoid(Z)
A


array([[0.89090318, 0.94267582, 0.09975049],
       [0.9939402 , 0.99183743, 0.01477403],
       [0.99969655, 0.99888746, 0.00202532]])

## Building a Real Design Matrix (US House Prices Dataset)
**Now we connect everything to a real dataset.**

I have a kaggle not book of this that uses US housing prices dataset.
We’ll build a design matrix from these.

Load the dataset

In [ ]:
'''TODO create a file to create a dataset for the github repo version

import pandas as pd

df = pd.read_csv("house_prices.csv")
df.head()'''

In [ ]:
'''
features = ["sqft_living", "bedrooms", "bathrooms"]
target = "price"

X = df[features].values  # shape (n, d)
y = df[target].values.reshape(-1, 1)
X.shape, y.shape

# add a bias column for ols
X_ols = np.column_stack([np.ones(len(X)), X])
X_ols.shape

#ols solution
beta = np.linalg.inv(X_ols.T @ X_ols) @ (X_ols.T @ y)
beta

# predictions
y_hat = X_ols @ beta
y_hat[:5]

'''

## This is the exact same structure as:

- linear regression
- logistic regression
- neural network layers
- Everything is built on:

𝑋𝑊 + 𝑏

# Final Summary: The Unifying Structure
**You’ve now seen the entire descent:**

- Single‑input linear regression
- Multi‑input dot product
- Matrix form (Xw + b)
- Logistic regression (sigmoid on top)
- Neural network layer (XW + b)

Real design matrix from real data

**The entire field of supervised learning is built from:**

- Linear transformation 𝑋𝑊 + 𝑏

- Nonlinearity 𝑓(⋅)

**Stack these two ideas and you get:**

- regression
- classification
- deep neural networks
- transformers
- everything

This project completes your first‑principles foundation.